## 아나콘다와 주피터의 관계

Anaconda(하이마트)

 - Python을 설치하는 방법
 - Jupyter도 설치됨
 
Jupyter(에어콘)

- Python을 사용하는 방법

## 대표값

In [1]:
import numpy

In [54]:
x = [100, 100, 100, 120, 200, 300, 300, 400, 500, 500, 600, 610, 700, 800, 900]

In [38]:
numpy.mean(x)  # 평균

240.0

In [25]:
numpy.median(x)  # 중간값

200.0

In [20]:
!pip install scipy

In [21]:
from scipy.stats import mode

In [28]:
mode(x)  # 최빈값

ModeResult(mode=array([100]), count=array([2]))

## 산포도

In [32]:
numpy.min(x)  # 최소

100

In [33]:
numpy.max(x)  # 최대

500

In [42]:
numpy.var(x)  # 분산

22400.0

In [43]:
numpy.std(x)  # 표준편차

149.66629547095766

In [55]:
numpy.quantile(x, .25)  # 1사분위수(25% 지점)

160.0

In [51]:
numpy.quantile(x, .5)

400.0

In [52]:
numpy.median(x)

400.0

In [53]:
numpy.quantile(x, .75)  # 3사분위수(75% 지점)

625.0

In [ ]:
x = [0, 0, 0, 0, 0, 0, 0, 0, 0, 100]

## 이항분포

In [56]:
from numpy.random import binomial

In [79]:
x = binomial(100, .3, 30)

In [80]:
min(x)

16

In [81]:
max(x)

42

In [82]:
x

array([32, 33, 28, 24, 31, 24, 29, 34, 32, 34, 16, 27, 23, 33, 34, 38, 28,
       27, 40, 24, 36, 36, 26, 26, 42, 29, 26, 22, 21, 28])

In [83]:
수익 = 0
준비 = 20
for 고객수 in x:
    if 고객수 <= 준비:
        수익 = 수익 + (준비 - 고객수) * -10000
        수익 = 수익 + 고객수 * 1000
    else:
        수익 = 수익 + 준비 * 1000
수익

556000

In [109]:
보험료 = 300
지급액 = 1000
고객 = 지급액 / 10
장사 = 100
사망자 = binomial(고객, .1, 장사)
매출 = 보험료 * 고객
지급 = 지급액 * 사망자
numpy.mean(매출 - 지급)

19790.0

In [105]:
binomial(100, .3)

30

## 기하분포

In [144]:
이탈성공 = 0
기간 = 0
while 이탈성공 == 0:
    이탈성공 = binomial(1, .05)
    기간 = 기간 + 1
기간

36

In [145]:
from numpy.random import geometric

In [160]:
기간 = geometric(.05, 100) # 이탈률 5%일 때 100명의 고객이 며칠 후 이탈하는지

## 음이항 분포

In [ ]:
negative_binomial(1, .05, 100)

In [171]:
numpy.sum(기간 * 0.5 - 10)

-130.0

In [163]:
numpy.sum(기간 * 1 - 100)

-8260

In [167]:
numpy.sum(기간 * 0.5 - 10 )

-130.0

In [181]:
폭발 = []
for i in range(100):
    짜증 = 0
    기간 = 0
    while 짜증 < 3:             # 3번째는 못 참는다
        사건 = binomial(1, .05) # 5%의 확률로 사건 발생
        if 사건 == 1:           # 사건이 나면
            짜증 = 짜증 + 1     # 짜증이 증가
        기간 = 기간 + 1   
    폭발.append(기간)

In [178]:
from numpy.random import negative_binomial

In [188]:
negative_binomial(3, .05)  # 5% 확률로 짜증이 나고 3번 나면 폭발
                           # 할 때까지 기간

68

In [189]:
negative_binomial(3, .05, 100)  # 100마리 리트리버

array([169,  98,  91,  62,  41,  31,  48,  20, 134,  52,  10,  50, 102,
        71,  34,  22,  40, 106,  24,  59,  45,  48,  19,  77,  24,  24,
        34, 114,  24,  68,  16,  30,  37,  21, 180, 143,  49, 126,  15,
        18,  66,  31,  56,  29,  76,  26,  16,  21,  39,  23, 105,  22,
       141,  33,  14,  92,  30,  44,  46,  50,  21,  77,  24,  62,  41,
        89,  31,  41,  66, 208,  12, 101,  35, 129,  76,  74,  58,  63,
         9,  49, 205,  21,  45,   7,  72,  37,  97,  69,  31,  54,  42,
        25,  95,  10,  85,  61,  51,  80,  80,  59])

## 실습

우리 리트리버는 10%의 확률로 짜증이 납니다. 이틀 연속으로 짜증이 나면 화를 냅니다. 리트리버가 화를 낼 때까지 기간을 시뮬레이션 해보세요.

## 포아송 분포

In [183]:
from numpy.random import poisson

In [187]:
binomial(100, .3, 50) # 100명의 고객이 30%로 방문할 때

array([31, 26, 36, 35, 27, 34, 29, 29, 26, 28, 28, 33, 36, 36, 26, 24, 23,
       25, 28, 34, 31, 29, 33, 30, 26, 27, 27, 30, 34, 27, 33, 29, 33, 29,
       23, 31, 32, 29, 33, 35, 33, 25, 29, 40, 25, 26, 28, 28, 28, 38])

In [185]:
poisson(30, 50)  # 하루 평균 30명 방문할 때 50일간 방문인원 수

array([28, 28, 31, 30, 25, 28, 25, 33, 25, 26, 33, 25, 36, 35, 38, 33, 25,
       18, 31, 36, 39, 35, 28, 27, 22, 29, 33, 29, 40, 22, 25, 20, 34, 35,
       31, 26, 15, 26, 41, 24, 30, 34, 40, 25, 34, 28, 21, 27, 31, 33, 29,
       28, 21, 25, 31, 40, 28, 31, 32, 28, 26, 24, 37, 25, 23, 27, 38, 29,
       30, 36, 34, 25, 37, 24, 35, 30, 30, 30, 32, 25, 39, 36, 28, 36, 30,
       28, 27, 25, 36, 27, 25, 30, 20, 25, 35, 33, 24, 29, 31, 28])

## 균등 분포

In [190]:
from numpy.random import uniform

In [212]:
uniform(10, 20)  # 최소값 10에서 최대값 20까지 사이에서 균등하게 

12.60608129437608

In [252]:
uniform(1, 10)  # 최소값 10에서 최대값 20까지 사이에서 균등하게 

5.976454583975816

In [221]:
uniform(0, 1)

0.21294424244455745

In [261]:
x = uniform(-1, 1, 1000)
y = uniform(-1, 1, 1000)

In [264]:
numpy.mean(numpy.abs(x) + numpy.abs(y) < 1)

0.503

In [268]:
x = uniform(-1, 1, 100000)
y = uniform(-1, 1, 100000)

In [271]:
numpy.mean(x ** 2 + y ** 2 < 1) * 4

3.14068

## 정규분포

In [272]:
from numpy.random import normal

In [325]:
기간 = geometric(.05, 100)

In [326]:
하루매출 = normal(50, 20, 100)  # 고객 100명이 평균 50만원(표준편차 20만원)

In [327]:
기간 * 하루매출

array([3212.5922976 , 4248.4194616 , 2667.76223606,  346.50680835,
       2047.87437038,  128.79513117, 1627.60471072,  246.0554823 ,
       2242.99825991,  409.36616026, 1719.654805  ,  917.58338778,
         52.0397216 ,  172.15091072, 2606.05806636,  503.14428624,
        329.00785213,  925.70555817, 1492.69856764,  751.09585656,
        968.66889448,  593.2071448 ,  495.3166062 ,  829.94594958,
       1116.4032001 , 1247.12070679,  211.85022547,  193.08130076,
       2809.83924333, 1325.28861165,  816.70205597,  161.41544145,
        661.55712627,  185.83329802,  209.74236507,  207.68920295,
       1406.09668523,  232.22101683,  206.389655  , 1387.08098416,
        980.1424612 ,  968.91910188, 1244.01098995,  542.51192673,
        408.13439391, 3598.92292493, 1946.81554274,  809.52705318,
        864.39801929,  345.0196083 ,  193.70173755, 1172.4019879 ,
        718.14373441,  349.4346808 ,  175.65918693,  818.52634196,
       1365.96918607, 1846.03693456,  336.96236638, 1689.51796

## 두 개의 정규분포가 섞여 있을 때

In [328]:
유저집단 = binomial(1, .1, 100)  # 헤비유저 10%

In [330]:
총매출 = []
for 유저 in 유저집단:
    if 유저 == 0: # 라이트 유저
        매출 = normal(30, 10)
    else:  # 헤비 유저
        매출 = normal(100, 10)
    총매출.append(매출)

In [366]:
numpy.mean(normal(10, 2, 100))

10.073064672320486

In [331]:
총매출

[34.10522609161714,
 120.33816743198119,
 42.883225004792116,
 111.88350189760868,
 111.36904475890238,
 24.880772504564227,
 100.72139657925773,
 101.69578399933533,
 87.45315036823553,
 27.898422720634613,
 30.470700355717458,
 27.331705860977983,
 32.52020501786026,
 23.349824589741637,
 36.62608933555686,
 29.372484498589493,
 15.891155483013595,
 28.10779850059054,
 94.25239309287554,
 25.614582598844343,
 22.11840442682858,
 24.35810595703015,
 31.887185070168258,
 131.62620291273447,
 93.10077293727964,
 34.72601496644473,
 14.548222473249995,
 24.51718495237473,
 94.65414750003055,
 34.97954796642996,
 95.42985405178001,
 78.85878925258261,
 101.80149687585458,
 17.542177087931584,
 90.82178712421347,
 41.62597144132264,
 107.8150360415745,
 85.46042241544652,
 18.637451800844353,
 97.44514382360236,
 92.04072932343757,
 103.98146104325475,
 91.51285702739308,
 34.13885208520713,
 101.93039898130472,
 83.54880519765608,
 25.53672439380733,
 108.34330777560379,
 77.9538633847805

## 다항분포

In [367]:
from numpy.random import multinomial

In [377]:
multinomial(10, [.5, .2, .2, .1])

array([7, 2, 1, 0])

In [378]:
multinomial(10, [.3, .7])

array([2, 8])

In [379]:
binomial(10, .3)

3

In [390]:
multinomial(100, [.5, .3, .2], 30) # 하루에 100명의 고객을 30일치

array([[46, 34, 20],
       [48, 29, 23],
       [55, 30, 15],
       [45, 35, 20],
       [54, 30, 16],
       [48, 27, 25],
       [58, 23, 19],
       [51, 27, 22],
       [50, 28, 22],
       [58, 28, 14],
       [52, 29, 19],
       [50, 25, 25],
       [55, 26, 19],
       [49, 27, 24],
       [48, 30, 22],
       [61, 23, 16],
       [51, 24, 25],
       [43, 31, 26],
       [57, 23, 20],
       [48, 31, 21],
       [55, 30, 15],
       [52, 34, 14],
       [45, 29, 26],
       [39, 34, 27],
       [52, 27, 21],
       [55, 33, 12],
       [39, 34, 27],
       [41, 38, 21],
       [47, 32, 21],
       [54, 28, 18]])

## 지수분포

In [391]:
from numpy.random import exponential

In [436]:
알바 = 10
리드타임 = 10 / 알바
numpy.mean(exponential(30, 1000) < 리드타임) # 리드타임 이내 도착 고객 비율

0.033